wekan:
  image: mquandalle/wekan
  links: 
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://0.0.0.0:8080 # ポートは好きなポートに
  ports:
    - 8080:80 # ポートは好きなポートに
  restart: always

wekandb:
  image: mongo
  volumes:
    - /srv/docker/dockerlab/wecan/data:/data/db 
    - /srv/docker/dockerlab/wecan/configdb:/data/configdb
  restart: always
